import { EventData } from "~/util/interface/EventData";
import { EventId } from "~/util/interface/EventId";
import { enterCastle } from "./enterCastle";
import { enterTower } from "./enterTower";
import { exitCastle } from "./exitCastle";
import { map2story } from "./map2story";
import { map8story } from "./map8story";
import { map10story } from "./map10story";
import { map11story } from "./map11story";
import { map16story } from "./map16story";
import { map17story } from "./map17story";
import { map18story } from "./map18story";
import { towerOpenSesame } from "./towerOpenSesame";
import { towerStairs1 } from "./towerStairs1";
import { towerStairs2 } from "./towerStairs2";
import { map19story } from "./map19story";
import { towerStairs3 } from "./towerStairs3";
import { map20story } from "./map20story";
import { towerStairs4 } from "./towerStairs4";
import { towerStairs5 } from "./towerStairs5";
import { map22story } from "./map22story";
import { crossingTheLine } from "./crossingTheLine";
import { enterChamber } from "./enterChamber";
import { map23story } from "./map23story";
import { killWizard } from "./killWizard";
import { map24story } from "./map24story";

export const eventMap: Map<EventId, EventData> = new Map();

eventMap.set("map2story", map2story);
eventMap.set("map8story", map8story);
eventMap.set("map10story", map10story);
eventMap.set("map11story", map11story);
eventMap.set("map16story", map16story);
eventMap.set("map17story", map17story);
eventMap.set("map18story", map18story);
eventMap.set("map19story", map19story);
eventMap.set("map20story", map20story);
eventMap.set("map22story", map22story);
eventMap.set("map23story", map23story);
eventMap.set("map24story", map24story);
eventMap.set("towerOpenSesame", towerOpenSesame);
eventMap.set("towerStairs1", towerStairs1);
eventMap.set("towerStairs2", towerStairs2);
eventMap.set("towerStairs3", towerStairs3);
eventMap.set("towerStairs4", towerStairs4);
eventMap.set("towerStairs5", towerStairs5);
eventMap.set("enterCastle", enterCastle);
eventMap.set("exitCastle", exitCastle);
eventMap.set("enterTower", enterTower);
eventMap.set("enterChamber", enterChamber);
eventMap.set("crossingTheLine", crossingTheLine)
eventMap.set("killWizard", killWizard);