export const tiles1 = {
    textureMap: new Map([
        ["cd00", "map/castle/castleDoor00.png"],
        ["cd01", "map/castle/castleDoor01.png"],
        ["cd02", "map/castle/castleDoor02.png"],
        ["cd10", "map/castle/castleDoor10.png"],
        ["cd11", "map/castle/castleDoor11.png"],
        ["cd12", "map/castle/castleDoor12.png"],
        ["cd20", "map/castle/castleDoor20.png"],
        ["cd21", "map/castle/castleDoor21.png"],
        ["cd22", "map/castle/castleDoor22.png"],
        ["cd_s", "map/castle/castleDoor_s.png"],
        ["cs00", "map/castle/castleSlope00.png"],
        ["cs10", "map/castle/castleSlope10.png"],
        ["cs20", "map/castle/castleSlope20.png"],
        ["cs30", "map/castle/castleSlope30.png"],
        ["cs01", "map/castle/castleSlope01.png"],
        ["cs11", "map/castle/castleSlope11.png"],
        ["cs21", "map/castle/castleSlope21.png"],
        ["cs31", "map/castle/castleSlope31.png"],
        ["cw00", "map/castle/castleWall00.png"],
        ["cw01", "map/castle/castleWall01.png"],
        ["cw02", "map/castle/castleWall02.png"],
        ["gf00", "map/floor/grassFloor00.png"],
        ["gf01", "map/floor/grassFloor01.png"],
        ["gf02", "map/floor/grassFloor02.png"],
        ["gf10", "map/floor/grassFloor10.png"],
        ["gf11", "map/floor/grassFloor11.png"],
        ["gf12", "map/floor/grassFloor12.png"],
        ["gf20", "map/floor/grassFloor20.png"],
        ["gf21", "map/floor/grassFloor21.png"],
        ["gf22", "map/floor/grassFloor22.png"],
        ["gf_s", "map/floor/grassFloor_s.png"],
        ["rd00", "map/road/road00.png"],
        ["rd01", "map/road/road01.png"],
        ["rd02", "map/road/road02.png"],
        ["rd10", "map/road/road10.png"],
        ["rd11", "map/road/road11.png"],
        ["rd12", "map/road/road12.png"],
        ["rd20", "map/road/road20.png"],
        ["rd21", "map/road/road21.png"],
        ["rd22", "map/road/road22.png"],
        ["rd_00", "map/road/road_00.png"],
        ["rd_01", "map/road/road_01.png"],
        ["rd_10", "map/road/road_10.png"],
        ["rd_11", "map/road/road_11.png"],
    ]),
    mapData: [
        [
            { texture: "cw00", passable: false, event: [], warp: null },
            { texture: "cw00", passable: false, event: [], warp: null },
            { texture: "cs00", passable: false, event: [], warp: null },
            { texture: "cd_s", passable: false, event: [], warp: null },
            { texture: "cd_s", passable: false, event: [], warp: null },
            { texture: "cd_s", passable: false, event: [], warp: null },
            { texture: "cs01", passable: false, event: [], warp: null },
            { texture: "cw00", passable: false, event: [], warp: null },
        ],
        [
            { texture: "cw01", passable: false, event: [], warp: null },
            { texture: "cw01", passable: false, event: [], warp: null },
            { texture: "cs10", passable: false, event: [], warp: null },
            { texture: "cd00", passable: false, event: [], warp: null },
            { texture: "cd01", passable: false, event: [], warp: null },
            { texture: "cd02", passable: false, event: [], warp: null },
            { texture: "cs11", passable: false, event: [], warp: null },
            { texture: "cw01", passable: false, event: [], warp: null },
        ],
        [
            { texture: "cw01", passable: false, event: [], warp: null },
            { texture: "cw01", passable: false, event: [], warp: null },
            { texture: "cs20", passable: false, event: [], warp: null },
            { texture: "cd10", passable: false, event: [], warp: null },
            { texture: "cd11", passable: false, event: [], warp: null },
            { texture: "cd12", passable: false, event: [], warp: null },
            { texture: "cs21", passable: false, event: [], warp: null },
            { texture: "cw01", passable: false, event: [], warp: null },
        ],
        [
            { texture: "cw02", passable: false, event: [], warp: null },
            { texture: "cw02", passable: false, event: [], warp: null },
            { texture: "cs30", passable: false, event: [], warp: null },
            { texture: "cd20", passable: false, event: [], warp: null },
            { texture: "cd21", passable: true, event: [], warp: null },
            { texture: "cd22", passable: false, event: [], warp: null },
            { texture: "cs31", passable: false, event: [], warp: null },
            { texture: "cw02", passable: false, event: [], warp: null },
        ],
        [
            { texture: "gf21", passable: true, event: [], warp: null },
            { texture: "gf21", passable: true, event: [], warp: null },
            { texture: "gf21", passable: true, event: [], warp: null },
            { texture: "rd10", passable: true, event: [], warp: null },
            { texture: "rd11", passable: true, event: [], warp: null },
            { texture: "rd12", passable: true, event: [], warp: null },
            { texture: "gf21", passable: true, event: [], warp: null },
            { texture: "gf21", passable: true, event: [], warp: null },
        ],
        [
            { texture: "gf_s", passable: true, event: [], warp: null },
            { texture: "gf_s", passable: true, event: [], warp: null },
            { texture: "gf_s", passable: true, event: [], warp: null },
            { texture: "rd10", passable: true, event: [], warp: null },
            { texture: "rd11", passable: true, event: [], warp: null },
            { texture: "rd12", passable: true, event: [], warp: null },
            { texture: "gf_s", passable: true, event: [], warp: null },
            { texture: "gf_s", passable: true, event: [], warp: null },
        ],
        [
            { texture: "gf_s", passable: true, event: [], warp: null },
            { texture: "gf_s", passable: true, event: [], warp: null },
            { texture: "gf_s", passable: true, event: [], warp: null },
            { texture: "rd10", passable: true, event: [], warp: null },
            { texture: "rd11", passable: true, event: [], warp: null },
            { texture: "rd12", passable: true, event: [], warp: null },
            { texture: "gf_s", passable: true, event: [], warp: null },
            { texture: "gf_s", passable: true, event: [], warp: null },
        ],
    ]
}