export const tileCI3 = {
    textureMap: new Map([
        ["cic00", "map/castleInterior/castleInCarpet00.png"],
        ["cic01", "map/castleInterior/castleInCarpet01.png"],
        ["cic02", "map/castleInterior/castleInCarpet02.png"],
        ["cic10", "map/castleInterior/castleInCarpet10.png"],
        ["cic11", "map/castleInterior/castleInCarpet11.png"],
        ["cic12", "map/castleInterior/castleInCarpet12.png"],
        ["cic20", "map/castleInterior/castleInCarpet20.png"],
        ["cic21", "map/castleInterior/castleInCarpet21.png"],
        ["cic22", "map/castleInterior/castleInCarpet22.png"],
        ["cic_00", "map/castleInterior/castleInCarpet_00.png"],
        ["cic_01", "map/castleInterior/castleInCarpet_01.png"],
        ["cic_10", "map/castleInterior/castleInCarpet_10.png"],
        ["cic_11", "map/castleInterior/castleInCarpet_11.png"],
        ["cf", "map/castleInterior/castleInFloor00.png"],
        ["ciw00", "map/castleInterior/castleInWall00.png"],
        ["ciw01", "map/castleInterior/castleInWall01.png"],
        ["ciw02", "map/castleInterior/castleInWall02.png"],
        ["ciw10", "map/castleInterior/castleInWall10.png"],
        ["ciw11", "map/castleInterior/castleInWall11.png"],
        ["ciw12", "map/castleInterior/castleInWall12.png"],
        ["ciw20", "map/castleInterior/castleInWall20.png"],
        ["ciw21", "map/castleInterior/castleInWall21.png"],
        ["ciw22", "map/castleInterior/castleInWall22.png"],
    ]),
    mapData: [
        [
            { texture: "ciw01", passable: false, event: [], warp: null },
            { texture: "ciw01", passable: false, event: [], warp: null },
            { texture: "ciw01", passable: false, event: [], warp: null },
            { texture: "ciw01", passable: false, event: [], warp: null },
            { texture: "ciw01", passable: false, event: [], warp: null },
            { texture: "ciw01", passable: false, event: [], warp: null },
            { texture: "ciw01", passable: false, event: [], warp: null },
            { texture: "ciw01", passable: false, event: [], warp: null },
        ],
        [
            { texture: "ciw11", passable: false, event: [], warp: null },
            { texture: "ciw11", passable: false, event: [], warp: null },
            { texture: "ciw11", passable: false, event: [], warp: null },
            { texture: "ciw11", passable: false, event: [], warp: null },
            { texture: "ciw11", passable: false, event: [], warp: null },
            { texture: "ciw11", passable: false, event: [], warp: null },
            { texture: "ciw11", passable: false, event: [], warp: null },
            { texture: "ciw11", passable: false, event: [], warp: null },
        ],
        [
            { texture: "ciw21", passable: false, event: [], warp: null },
            { texture: "ciw21", passable: false, event: [], warp: null },
            { texture: "ciw21", passable: false, event: [], warp: null },
            { texture: "ciw21", passable: false, event: [], warp: null },
            { texture: "ciw21", passable: false, event: [], warp: null },
            { texture: "ciw21", passable: false, event: [], warp: null },
            { texture: "ciw21", passable: false, event: [], warp: null },
            { texture: "ciw21", passable: false, event: [], warp: null },
        ],
        [
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
        ],
        [
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cic00", passable: true, event: [], warp: null },
            { texture: "cic01", passable: true, event: [], warp: null },
            { texture: "cic01", passable: true, event: [], warp: null },
            { texture: "cic01", passable: true, event: [], warp: null },
            { texture: "cic01", passable: true, event: [], warp: null },
        ],
        [
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cic10", passable: true, event: [], warp: null },
            { texture: "cic_00", passable: true, event: [], warp: null },
            { texture: "cic21", passable: true, event: [], warp: null },
            { texture: "cic21", passable: true, event: [], warp: null },
            { texture: "cic21", passable: true, event: [], warp: null },
        ],
        [
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
            { texture: "cf", passable: true, event: [], warp: null },
        ],
    ]
}