import { MapData } from "../../objects/MapData";

export const map1 = new MapData([
    [
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
    ],
    [
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
    ],
    [
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
    ],
    [
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "bl", passable: false, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "bl", passable: false, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
    ],
    [
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "bl", passable: false, event: [], warp: null },
        { texture: "bl", passable: false, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
    ],
    [
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
    ],
    [
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
        { texture: "gr", passable: true, event: [], warp: null },
    ],
], new Map([
    ["bl", "objects/bloakcs.png"],
    ["gr", "objects/graas.png"]
]),
    []
)