import { MapData } from "../../util/interface/MapData";

export const map1: MapData = {
    textureMap: new Map([
        ["mi", "characters/crazy.png"],
        ["textArea", "ui/text.png"],
        ["bl", "objects/bloakcs.png"],
        ["gr", "objects/graas.png"]
    ]),
    mapData: [
        [
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
        ],
        [
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
        ],
        [
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
        ],
        [
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "bl", passable: false, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "bl", passable: false, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
        ],
        [
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "bl", passable: false, event: [], warp: null },
            { texture: "bl", passable: false, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
        ],
        [
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
        ],
        [
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
            { texture: "gr", passable: true, event: [], warp: null },
        ],
    ],
    textData: [],
    creatureData: []
};