import { MapData } from "~/util/interface/MapData";
import map10 from "./map10";
import map11 from "./map11";
import map12 from "./map12";
import map13 from "./map13";
import map14 from "./map14";
import map15 from "./map15";
import map16 from "./map16";
import map17 from "./map17";
import map2 from "./map2";
import map3 from "./map3";
import map4 from "./map4";
import map5 from "./map5";
import map6 from "./map6";
import map7 from "./map7";
import map8 from "./map8";
import map9 from "./map9";

export const mapMap: Map<string, MapData> = new Map();

mapMap.set("map2", map2);
mapMap.set("map3", map3);
mapMap.set("map4", map4);
mapMap.set("map5", map5);
mapMap.set("map6", map6);
mapMap.set("map7", map7);
mapMap.set("map8", map8);
mapMap.set("map9", map9);
mapMap.set("map10", map10);
mapMap.set("map11", map11);
mapMap.set("map12", map12);
mapMap.set("map13", map13);
mapMap.set("map14", map14);
mapMap.set("map15", map15);
mapMap.set("map16", map16);
mapMap.set("map17", map17);